logging:
  level:
    com.ilongli.rabbitmq: debug
spring:
  rabbitmq:
    host: 192.168.2.46
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true