logging:
  level:
    com.ilongli.rabbitmq: debug
spring:
  rabbitmq:
    host: 42.193.255.106
    port: 5672
    username: admin
    password: admin
    virtual-host: /bog
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true